get:
  summary: 元(Meta)数据
  tags:
    - 核心实体
  description: 提供VR元数据的查询，主要包括但不限于`标题、拍摄信息、渲染信息、Five中控参数`等
  parameters:
    - name: Authorization
      in: header
      description: 鉴权获取的access_token
      required: true
      schema:
        type: string
        default: your_access_token
    - name: vr_code
      in: query
      description: "VR 编码"
      required: true
      schema:
        type: string
        default: "80drj5DRZejY2Dq8Oe"
    - name: locale
      in: query
      description: "默认zh_CN暨中文，请参考https://docs.oracle.com/cd/E23824_01/html/E26033/glset.html"
      required: false
      schema:
        type: string
        default: "zh_CN"
  responses:
    200:
      content:
        application/json:
          schema:
            type: object
            properties:
              request_id:
                type: string
                description: "标识唯一一次请求"
              trace_id:
                type: string
                description: "标识唯一一次请求, 同 request_id 类似，但主要用于请求追溯的场景"
              code:
                type: integer
                description: "错误码，请求成功时默认为 0"
              status:
                type: string
                description: "错误信息，请求成功是默认为 success"
              cost:
                type: integer
                description: "服务端计算耗时，单位 ms"
              data:
                type: object
                properties:
                  status:
                    type: enums
                    description: "VR 状态"
                    enum:
                      [
                        "RENDER_DONE",
                        "RENDER_ING",
                        "RENDER_PART_DONE",
                        "RENDER_FAIL",
                      ]
                  detail:
                    type: object
                    description: "详情数据"
                    $ref: "#/components/schemas/Detail"
                  original:
                    type: object
                    description: "原始信息: 采集/渲染时数据"
                    $ref: "#/components/schemas/Original"
                  five:
                    type: object
                    description: "Five中控参数"
                    $ref: "#/components/schemas/Five"
components:
  schemas:
    Detail:
      type: object
      properties:
        name:
          type: string
          description: "VR 标题"
        source:
          type: string
          description: "VR 来源"
          default: "REALSEE"
        create_time:
          type: string
          description: "创建时间: 实景-项目创建时间; 虚拟-开始渲染时间"
        modify_time:
          type: string
          description: "更新时间"
        picture_url:
          type: string
          description: "封面图片"
        url:
          type: string
          description: "中心化服务预览链接"
    Five:
      type: object
      properties:
        auto_resize:
          type: boolean
          description: "是否自动缩放"
        min_fov:
          type: number
          description: "最小视角(Field Of View)"
        max_fov:
          type: number
          description: "最大视角(Field Of View)"
        tile_level:
          type: number
          description: "瓦片等级: 0-4"
    Original:
      type: object
      properties:
        name:
          type: string
          description: "拍摄设备名称"
        bg_image:
          type: string
          description: "拍摄设备图片"
        principle:
          type: string
          description: "采集引擎"
        outer_edge_group_id:
          type: string
          description: "户型组ID"
          default: "cba55c60-f4c0-4ff4-b0c1-2e859763d137"
        style_id:
          type: string 
          description: "风格ID"
          default: "3" 
        style_name:
          type: string
          description: "风格名"
          default: "灰白简约"
        cube_size:
          type: string
          description: "全景Cube图尺寸"
          default: "2048"
